
package expedientessancionadores;

/**
 *
 * @author Maria Corpas
 */

public class Interfaz extends javax.swing.JFrame {
    //AQUÍ VAN LOS ATRIBUTOS
    Carnet carnet = new Carnet();
    Conductor conductor = new Conductor();
    /**
     * Creates new form Interfaz
     * ¡IMPORTANTE!
     * Explicación del criterio seguido para nombrar elementos de la interfaz:
     *      Todos los botones tendrán delante el nombre de Boton + la función de dicho botón.
     *      Todas las etiquetas llevarán en el nombre Etiqueta + el texto de la etiqueta.
     *      Todas los jTextField/JComboBox/JTextPane llevarán el nombre asociado a la etiqueta que corresponde.
     * Además de lo anterior, todos los elementos (excepto los Jpanel) llevarán al final de cada nombre las iniciales (en mayúsculas) del panel en el que se encuentra:
     *      Login : L
     *      Agente : A
     *      Conductor : C
     *      TrabajadorDGT : TD
     *      AltaConductor : AC
     *      PopUpConfirma : C
     *      PopUpPagar : P
     *      PopUpConfirma : C
     *      PopUpBajaConductor : BC
     *      PopUpRealizarBusqueda : RB
     *
     * 
     */
    public Interfaz() {
        initComponents();
        TrabajadorDGT.setVisible(false);
        Agente.setVisible(false);
        Conductor.setVisible(false);
        AltaConductor.setVisible(false);
        PopUpPagar.setVisible(false);
        PopUpConfirma.setVisible(false);
        PopUpBajaConductor.setVisible(false);
        PopUpRealizarBusqueda.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PopUpPagar = new javax.swing.JDialog();
        EtiquetaTarjetaP = new javax.swing.JLabel();
        TarjetaP = new javax.swing.JTextField();
        BotonPagarP = new javax.swing.JButton();
        PopUpConfirma = new javax.swing.JDialog();
        EtiquetaConfirmaC = new javax.swing.JLabel();
        BotonAceptarC = new javax.swing.JButton();
        PopUpBajaConductor = new javax.swing.JDialog();
        EtiquetaEscribirBC = new javax.swing.JLabel();
        DniBC = new javax.swing.JTextField();
        DarBajaBC = new javax.swing.JButton();
        PopUpRealizarBusqueda = new javax.swing.JDialog();
        EtiquetaBuscarRB = new javax.swing.JLabel();
        DniRB = new javax.swing.JTextField();
        BuscarRB = new javax.swing.JButton();
        TrabajadorDGT = new javax.swing.JPanel();
        BotonAltaConductorTD = new javax.swing.JButton();
        BotonBajaConductorTD = new javax.swing.JButton();
        BotonBuscarConductorTD = new javax.swing.JButton();
        BotonModificarConductorTD = new javax.swing.JButton();
        Login = new javax.swing.JPanel();
        EtiquetaNombreL = new javax.swing.JLabel();
        EtiquetaPasswordL = new javax.swing.JLabel();
        EtiquetaTipoL = new javax.swing.JLabel();
        BotonEntrarL = new javax.swing.JButton();
        NombreL = new javax.swing.JTextField();
        TipoL = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        BaseDatosLeidaL = new javax.swing.JTextPane();
        PasswordL = new javax.swing.JPasswordField();
        Agente = new javax.swing.JPanel();
        BotonCrearDenunciaA = new javax.swing.JButton();
        EtiquetaCodigoA = new javax.swing.JLabel();
        EtiquetaImporteA = new javax.swing.JLabel();
        CodigoA = new javax.swing.JTextField();
        ImporteA = new javax.swing.JTextField();
        EtiquetaCausaA = new javax.swing.JLabel();
        CausaA = new javax.swing.JTextField();
        EtiquetaDatoA = new javax.swing.JLabel();
        DatoA = new javax.swing.JComboBox<>();
        EtiquetaMatriculaA = new javax.swing.JLabel();
        MatriculaA = new javax.swing.JTextField();
        EtiquetaDniConductorA = new javax.swing.JLabel();
        DniConductorA = new javax.swing.JTextField();
        Conductor = new javax.swing.JPanel();
        EtiquetaNombreC = new javax.swing.JLabel();
        EtiquetaDniC = new javax.swing.JLabel();
        EtiquetaMatriculasC = new javax.swing.JLabel();
        MostrarNombreC = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        MostrarDniC = new javax.swing.JScrollPane();
        jTextPane2 = new javax.swing.JTextPane();
        MostrarMatrículasC = new javax.swing.JScrollPane();
        jTextPane3 = new javax.swing.JTextPane();
        DenunciasC = new javax.swing.JComboBox<>();
        EtiquetaDenunciasC = new javax.swing.JLabel();
        BotonPresentarAlegacionC = new javax.swing.JButton();
        BotonPagarDenunciaC = new javax.swing.JButton();
        EtiquetaFechaC = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        EtiquetaC = new javax.swing.JTextPane();
        AltaConductor = new javax.swing.JPanel();
        EtiquetaNombreAC = new javax.swing.JLabel();
        EtiquetaApellidoAC = new javax.swing.JLabel();
        EtiquetaCalleAC = new javax.swing.JLabel();
        EtiquetaDniAC = new javax.swing.JLabel();
        EtiquetaEmailAC = new javax.swing.JLabel();
        EtiquetaGafasLentillasAC = new javax.swing.JLabel();
        EtiquetaContraseñaAC = new javax.swing.JLabel();
        NombreAC = new javax.swing.JTextField();
        ApellidosAC = new javax.swing.JTextField();
        CalleAC = new javax.swing.JTextField();
        DniAC = new javax.swing.JTextField();
        EmailAC = new javax.swing.JTextField();
        GafasLentillasAC = new javax.swing.JComboBox<>();
        PasswordAC = new javax.swing.JPasswordField();
        BotonRegistrarAC = new javax.swing.JButton();

        PopUpPagar.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        PopUpPagar.setTitle("Proceso de pago");
        PopUpPagar.setLocationByPlatform(true);
        PopUpPagar.setSize(new java.awt.Dimension(800, 200));
        PopUpPagar.setType(java.awt.Window.Type.POPUP);

        EtiquetaTarjetaP.setText("Escriba el número de su tarjeta de crédito");

        BotonPagarP.setText("Pagar denuncia");
        BotonPagarP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonPagarPActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PopUpPagarLayout = new javax.swing.GroupLayout(PopUpPagar.getContentPane());
        PopUpPagar.getContentPane().setLayout(PopUpPagarLayout);
        PopUpPagarLayout.setHorizontalGroup(
            PopUpPagarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PopUpPagarLayout.createSequentialGroup()
                .addGroup(PopUpPagarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PopUpPagarLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(EtiquetaTarjetaP)
                        .addGap(53, 53, 53)
                        .addComponent(TarjetaP, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PopUpPagarLayout.createSequentialGroup()
                        .addGap(235, 235, 235)
                        .addComponent(BotonPagarP, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PopUpPagarLayout.setVerticalGroup(
            PopUpPagarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PopUpPagarLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(PopUpPagarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EtiquetaTarjetaP)
                    .addComponent(TarjetaP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(BotonPagarP)
                .addContainerGap(61, Short.MAX_VALUE))
        );

        PopUpConfirma.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        PopUpConfirma.setTitle("Confirmación de pago");
        PopUpConfirma.setSize(new java.awt.Dimension(400, 300));

        EtiquetaConfirmaC.setText("Se ha pagado la denuncia de forma correcta");

        BotonAceptarC.setText("Aceptar");
        BotonAceptarC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonAceptarCActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PopUpConfirmaLayout = new javax.swing.GroupLayout(PopUpConfirma.getContentPane());
        PopUpConfirma.getContentPane().setLayout(PopUpConfirmaLayout);
        PopUpConfirmaLayout.setHorizontalGroup(
            PopUpConfirmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PopUpConfirmaLayout.createSequentialGroup()
                .addGroup(PopUpConfirmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PopUpConfirmaLayout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(EtiquetaConfirmaC, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PopUpConfirmaLayout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addComponent(BotonAceptarC)))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        PopUpConfirmaLayout.setVerticalGroup(
            PopUpConfirmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PopUpConfirmaLayout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(EtiquetaConfirmaC)
                .addGap(74, 74, 74)
                .addComponent(BotonAceptarC)
                .addContainerGap(120, Short.MAX_VALUE))
        );

        PopUpBajaConductor.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        PopUpBajaConductor.setTitle("Baja Usuario");
        PopUpBajaConductor.setSize(new java.awt.Dimension(400, 300));

        EtiquetaEscribirBC.setText("Escriba el dni del conductor a dar de baja");

        DarBajaBC.setText("Dar de baja");

        javax.swing.GroupLayout PopUpBajaConductorLayout = new javax.swing.GroupLayout(PopUpBajaConductor.getContentPane());
        PopUpBajaConductor.getContentPane().setLayout(PopUpBajaConductorLayout);
        PopUpBajaConductorLayout.setHorizontalGroup(
            PopUpBajaConductorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PopUpBajaConductorLayout.createSequentialGroup()
                .addGroup(PopUpBajaConductorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PopUpBajaConductorLayout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addGroup(PopUpBajaConductorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(EtiquetaEscribirBC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(DniBC)))
                    .addGroup(PopUpBajaConductorLayout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addComponent(DarBajaBC)))
                .addContainerGap(88, Short.MAX_VALUE))
        );
        PopUpBajaConductorLayout.setVerticalGroup(
            PopUpBajaConductorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PopUpBajaConductorLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(EtiquetaEscribirBC)
                .addGap(61, 61, 61)
                .addComponent(DniBC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(DarBajaBC)
                .addContainerGap(66, Short.MAX_VALUE))
        );

        PopUpRealizarBusqueda.setSize(new java.awt.Dimension(400, 300));

        EtiquetaBuscarRB.setText("Escribe el dni del conductor a buscar");

        BuscarRB.setText("Buscar");

        javax.swing.GroupLayout PopUpRealizarBusquedaLayout = new javax.swing.GroupLayout(PopUpRealizarBusqueda.getContentPane());
        PopUpRealizarBusqueda.getContentPane().setLayout(PopUpRealizarBusquedaLayout);
        PopUpRealizarBusquedaLayout.setHorizontalGroup(
            PopUpRealizarBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PopUpRealizarBusquedaLayout.createSequentialGroup()
                .addGroup(PopUpRealizarBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PopUpRealizarBusquedaLayout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addGroup(PopUpRealizarBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(EtiquetaBuscarRB, javax.swing.GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE)
                            .addComponent(DniRB)))
                    .addGroup(PopUpRealizarBusquedaLayout.createSequentialGroup()
                        .addGap(152, 152, 152)
                        .addComponent(BuscarRB)))
                .addContainerGap(88, Short.MAX_VALUE))
        );
        PopUpRealizarBusquedaLayout.setVerticalGroup(
            PopUpRealizarBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PopUpRealizarBusquedaLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(EtiquetaBuscarRB)
                .addGap(28, 28, 28)
                .addComponent(DniRB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67)
                .addComponent(BuscarRB)
                .addContainerGap(85, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setModalExclusionType(java.awt.Dialog.ModalExclusionType.APPLICATION_EXCLUDE);
        setName("Interfaz"); // NOI18N
        setResizable(false);

        TrabajadorDGT.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        BotonAltaConductorTD.setText("Alta conductor");
        BotonAltaConductorTD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonAltaConductorTDActionPerformed(evt);
            }
        });

        BotonBajaConductorTD.setText("Baja conductor");
        BotonBajaConductorTD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonBajaConductorTDActionPerformed(evt);
            }
        });

        BotonBuscarConductorTD.setText("Buscar conductor");
        BotonBuscarConductorTD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonBuscarConductorTDActionPerformed(evt);
            }
        });

        BotonModificarConductorTD.setText("Modificar conductor");
        BotonModificarConductorTD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonModificarConductorTDActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout TrabajadorDGTLayout = new javax.swing.GroupLayout(TrabajadorDGT);
        TrabajadorDGT.setLayout(TrabajadorDGTLayout);
        TrabajadorDGTLayout.setHorizontalGroup(
            TrabajadorDGTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TrabajadorDGTLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(TrabajadorDGTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BotonAltaConductorTD, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotonBuscarConductorTD, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(81, 81, 81)
                .addGroup(TrabajadorDGTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BotonModificarConductorTD, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotonBajaConductorTD, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(68, Short.MAX_VALUE))
        );
        TrabajadorDGTLayout.setVerticalGroup(
            TrabajadorDGTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TrabajadorDGTLayout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addGroup(TrabajadorDGTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotonAltaConductorTD)
                    .addComponent(BotonBajaConductorTD))
                .addGap(92, 92, 92)
                .addGroup(TrabajadorDGTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotonBuscarConductorTD)
                    .addComponent(BotonModificarConductorTD))
                .addGap(91, 91, 91))
        );

        Login.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Login.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Login.setName("Login"); // NOI18N

        EtiquetaNombreL.setText("Nombre");

        EtiquetaPasswordL.setText("Password");

        EtiquetaTipoL.setText("Tipo");

        BotonEntrarL.setText("Entrar");
        BotonEntrarL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonEntrarLActionPerformed(evt);
            }
        });

        TipoL.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Trabajador DGT", "Conductor", "Agente", "Dirección Provincial" }));
        TipoL.setSelectedIndex(-1);

        jScrollPane1.setViewportView(BaseDatosLeidaL);

        javax.swing.GroupLayout LoginLayout = new javax.swing.GroupLayout(Login);
        Login.setLayout(LoginLayout);
        LoginLayout.setHorizontalGroup(
            LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginLayout.createSequentialGroup()
                .addGroup(LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LoginLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(EtiquetaNombreL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(EtiquetaPasswordL, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                            .addComponent(EtiquetaTipoL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(65, 65, 65)
                        .addGroup(LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(NombreL, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
                            .addComponent(TipoL, 0, 192, Short.MAX_VALUE)
                            .addComponent(PasswordL)))
                    .addGroup(LoginLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(LoginLayout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(BotonEntrarL, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        LoginLayout.setVerticalGroup(
            LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(EtiquetaNombreL)
                    .addComponent(NombreL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addGroup(LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EtiquetaPasswordL)
                    .addComponent(PasswordL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LoginLayout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(EtiquetaTipoL))
                    .addGroup(LoginLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(TipoL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BotonEntrarL)
                .addGap(36, 36, 36)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );

        Agente.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        BotonCrearDenunciaA.setText("Crear denuncia");
        BotonCrearDenunciaA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonCrearDenunciaAActionPerformed(evt);
            }
        });

        EtiquetaCodigoA.setText("Código");

        EtiquetaImporteA.setText("Importe");

        EtiquetaCausaA.setText("Causa");

        EtiquetaDatoA.setText("Dato");

        DatoA.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Matrícula", "DNI conductor" }));
        DatoA.setSelectedIndex(-1);

        EtiquetaMatriculaA.setText("Matrícula");

        EtiquetaDniConductorA.setText("DNI conductor");

        javax.swing.GroupLayout AgenteLayout = new javax.swing.GroupLayout(Agente);
        Agente.setLayout(AgenteLayout);
        AgenteLayout.setHorizontalGroup(
            AgenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AgenteLayout.createSequentialGroup()
                .addGroup(AgenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AgenteLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(AgenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(EtiquetaCodigoA)
                            .addComponent(EtiquetaImporteA)
                            .addComponent(EtiquetaCausaA)
                            .addComponent(EtiquetaDatoA)
                            .addComponent(EtiquetaMatriculaA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(EtiquetaDniConductorA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(171, 171, 171)
                        .addGroup(AgenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(CodigoA)
                            .addComponent(ImporteA)
                            .addComponent(CausaA)
                            .addComponent(DatoA, 0, 218, Short.MAX_VALUE)
                            .addComponent(MatriculaA)
                            .addComponent(DniConductorA)))
                    .addGroup(AgenteLayout.createSequentialGroup()
                        .addGap(185, 185, 185)
                        .addComponent(BotonCrearDenunciaA)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        AgenteLayout.setVerticalGroup(
            AgenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AgenteLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(AgenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EtiquetaCodigoA)
                    .addComponent(CodigoA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(AgenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ImporteA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EtiquetaImporteA))
                .addGap(40, 40, 40)
                .addGroup(AgenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EtiquetaCausaA)
                    .addComponent(CausaA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(AgenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DatoA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EtiquetaDatoA))
                .addGap(27, 27, 27)
                .addGroup(AgenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EtiquetaMatriculaA)
                    .addComponent(MatriculaA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(AgenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EtiquetaDniConductorA)
                    .addComponent(DniConductorA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(BotonCrearDenunciaA)
                .addGap(27, 27, 27))
        );

        Conductor.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        EtiquetaNombreC.setText("Nombre");

        EtiquetaDniC.setText("DNI");

        EtiquetaMatriculasC.setText("Matrícula/s");

        MostrarNombreC.setViewportView(jTextPane1);

        MostrarDniC.setViewportView(jTextPane2);

        MostrarMatrículasC.setViewportView(jTextPane3);

        EtiquetaDenunciasC.setText("Mostrar denuncias");

        BotonPresentarAlegacionC.setText("Presentar Alegacion");
        BotonPresentarAlegacionC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonPresentarAlegacionCActionPerformed(evt);
            }
        });

        BotonPagarDenunciaC.setText("Pagar denuncia");
        BotonPagarDenunciaC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonPagarDenunciaCActionPerformed(evt);
            }
        });

        EtiquetaFechaC.setText("Fecha caducidad carnet");

        jScrollPane2.setViewportView(EtiquetaC);

        javax.swing.GroupLayout ConductorLayout = new javax.swing.GroupLayout(Conductor);
        Conductor.setLayout(ConductorLayout);
        ConductorLayout.setHorizontalGroup(
            ConductorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ConductorLayout.createSequentialGroup()
                .addGroup(ConductorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ConductorLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(ConductorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(EtiquetaNombreC)
                            .addComponent(EtiquetaDniC)
                            .addComponent(EtiquetaMatriculasC)
                            .addComponent(EtiquetaDenunciasC)
                            .addComponent(EtiquetaFechaC))
                        .addGap(134, 134, 134)
                        .addGroup(ConductorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(DenunciasC, 0, 240, Short.MAX_VALUE)
                            .addComponent(MostrarNombreC)
                            .addComponent(MostrarDniC)
                            .addComponent(MostrarMatrículasC)
                            .addComponent(jScrollPane2)))
                    .addGroup(ConductorLayout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addGroup(ConductorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(BotonPresentarAlegacionC, javax.swing.GroupLayout.DEFAULT_SIZE, 253, Short.MAX_VALUE)
                            .addComponent(BotonPagarDenunciaC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ConductorLayout.setVerticalGroup(
            ConductorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ConductorLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(ConductorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(EtiquetaNombreC)
                    .addComponent(MostrarNombreC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(ConductorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(EtiquetaDniC)
                    .addComponent(MostrarDniC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(ConductorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(EtiquetaMatriculasC)
                    .addComponent(MostrarMatrículasC, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ConductorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DenunciasC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EtiquetaDenunciasC))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(ConductorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(EtiquetaFechaC, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(BotonPresentarAlegacionC)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BotonPagarDenunciaC)
                .addGap(27, 27, 27))
        );

        AltaConductor.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        EtiquetaNombreAC.setText("Nombre");

        EtiquetaApellidoAC.setText("Apellidos");

        EtiquetaCalleAC.setText("Calle");

        EtiquetaDniAC.setText("DNI");

        EtiquetaEmailAC.setText("Email");

        EtiquetaGafasLentillasAC.setText("Gafas/Lentillas");

        EtiquetaContraseñaAC.setText("Contraseña");

        GafasLentillasAC.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Gafas", "Lentillas", "Nada" }));
        GafasLentillasAC.setSelectedIndex(-1);

        BotonRegistrarAC.setText("Registrar");
        BotonRegistrarAC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonRegistrarACActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AltaConductorLayout = new javax.swing.GroupLayout(AltaConductor);
        AltaConductor.setLayout(AltaConductorLayout);
        AltaConductorLayout.setHorizontalGroup(
            AltaConductorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AltaConductorLayout.createSequentialGroup()
                .addGroup(AltaConductorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AltaConductorLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(AltaConductorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(EtiquetaNombreAC)
                            .addComponent(EtiquetaApellidoAC)
                            .addComponent(EtiquetaCalleAC)
                            .addComponent(EtiquetaDniAC)
                            .addComponent(EtiquetaEmailAC)
                            .addComponent(EtiquetaGafasLentillasAC)
                            .addComponent(EtiquetaContraseñaAC))
                        .addGap(91, 91, 91)
                        .addGroup(AltaConductorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(NombreAC)
                            .addComponent(ApellidosAC)
                            .addComponent(CalleAC)
                            .addComponent(DniAC)
                            .addComponent(EmailAC)
                            .addComponent(GafasLentillasAC, 0, 206, Short.MAX_VALUE)
                            .addComponent(PasswordAC)))
                    .addGroup(AltaConductorLayout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(BotonRegistrarAC, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        AltaConductorLayout.setVerticalGroup(
            AltaConductorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AltaConductorLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(AltaConductorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EtiquetaNombreAC)
                    .addComponent(NombreAC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(AltaConductorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EtiquetaApellidoAC)
                    .addComponent(ApellidosAC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(AltaConductorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EtiquetaCalleAC)
                    .addComponent(CalleAC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(AltaConductorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EtiquetaDniAC)
                    .addComponent(DniAC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(AltaConductorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EtiquetaEmailAC)
                    .addComponent(EmailAC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(AltaConductorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EtiquetaGafasLentillasAC)
                    .addComponent(GafasLentillasAC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(AltaConductorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EtiquetaContraseñaAC)
                    .addComponent(PasswordAC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(BotonRegistrarAC)
                .addGap(27, 27, 27))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Login, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(AltaConductor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(TrabajadorDGT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Conductor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(Agente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(10, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Login, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(TrabajadorDGT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Conductor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(AltaConductor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(Agente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(404, Short.MAX_VALUE))
        );

        TrabajadorDGT.getAccessibleContext().setAccessibleName("Trabajador_DGT");
        Login.getAccessibleContext().setAccessibleName("Login");
        Login.getAccessibleContext().setAccessibleDescription("");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BotonBuscarConductorTDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonBuscarConductorTDActionPerformed
        // TODO add your handling code here:
        //Buscar un usuario
    }//GEN-LAST:event_BotonBuscarConductorTDActionPerformed

    private void BotonEntrarLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonEntrarLActionPerformed
        // TODO add your handling code here:
        //Dependiendo del usuario introducido se muestra un panel u otro
        //Si el usuario es Agente hay que controlar las vistas de los campos matrícua y dni conductor según la selección del dato.
        Login.setVisible(false);
        TrabajadorDGT.setVisible(true);
        Conductor.setVisible(true);
        
    }//GEN-LAST:event_BotonEntrarLActionPerformed

    private void BotonAltaConductorTDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonAltaConductorTDActionPerformed
        // TODO add your handling code here:
        //Creamos un conductor
        //Verificación del email
        //Verificación del dni (?)
        TrabajadorDGT.setVisible(false);
        AltaConductor.setVisible(true);
    }//GEN-LAST:event_BotonAltaConductorTDActionPerformed

    private void BotonBajaConductorTDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonBajaConductorTDActionPerformed
        // TODO add your handling code here:
        PopUpBajaConductor.setVisible(true);
        
    }//GEN-LAST:event_BotonBajaConductorTDActionPerformed

    private void BotonModificarConductorTDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonModificarConductorTDActionPerformed
        // TODO add your handling code here:
        //LLevar al panel del registro con todos los campos bloqueados y rellenos con la información del conductor excepto el cambio de domicilio y la fecha de renovación
        TrabajadorDGT.setVisible(false);
        AltaConductor.setVisible(true);
        BotonRegistrarAC.setName("Modificar Usuario");
        NombreAC.setEditable(false);
        ApellidosAC.setEditable(false);
        DniAC.setEditable(false);
        EmailAC.setEditable(false);
        GafasLentillasAC.setEditable(false);
        PasswordAC.setEditable(false); 
        
    }//GEN-LAST:event_BotonModificarConductorTDActionPerformed

    private void BotonCrearDenunciaAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonCrearDenunciaAActionPerformed
        // TODO add your handling code here:
        //Creamos la denuncia
    }//GEN-LAST:event_BotonCrearDenunciaAActionPerformed

    private void BotonRegistrarACActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonRegistrarACActionPerformed
        // TODO add your handling code here:
        //Creamos el conductor con los datos introducidos
    }//GEN-LAST:event_BotonRegistrarACActionPerformed

    private void BotonPresentarAlegacionCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonPresentarAlegacionCActionPerformed
        // TODO add your handling code here:
        //Creamos la alegación con los datos introducidos
    }//GEN-LAST:event_BotonPresentarAlegacionCActionPerformed

    private void BotonPagarDenunciaCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonPagarDenunciaCActionPerformed
        // TODO add your handling code here:
        //Pop up para introducir el número de la tarjeta de crédito y un botón que ponga pagar
        PopUpPagar.setVisible(true);
        
    }//GEN-LAST:event_BotonPagarDenunciaCActionPerformed

    private void BotonPagarPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonPagarPActionPerformed
        // TODO add your handling code here:
        //Pop up para avisar de que la denuncia ha sido pagada
        PopUpConfirma.setVisible(true);
        PopUpPagar.setVisible(false);
        
    }//GEN-LAST:event_BotonPagarPActionPerformed

    private void BotonAceptarCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonAceptarCActionPerformed
        // TODO add your handling code here:
        PopUpConfirma.setVisible(false);
    }//GEN-LAST:event_BotonAceptarCActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Agente;
    private javax.swing.JPanel AltaConductor;
    private javax.swing.JTextField ApellidosAC;
    private javax.swing.JTextPane BaseDatosLeidaL;
    private javax.swing.JButton BotonAceptarC;
    private javax.swing.JButton BotonAltaConductorTD;
    private javax.swing.JButton BotonBajaConductorTD;
    private javax.swing.JButton BotonBuscarConductorTD;
    private javax.swing.JButton BotonCrearDenunciaA;
    private javax.swing.JButton BotonEntrarL;
    private javax.swing.JButton BotonModificarConductorTD;
    private javax.swing.JButton BotonPagarDenunciaC;
    private javax.swing.JButton BotonPagarP;
    private javax.swing.JButton BotonPresentarAlegacionC;
    private javax.swing.JButton BotonRegistrarAC;
    private javax.swing.JButton BuscarRB;
    private javax.swing.JTextField CalleAC;
    private javax.swing.JTextField CausaA;
    private javax.swing.JTextField CodigoA;
    private javax.swing.JPanel Conductor;
    private javax.swing.JButton DarBajaBC;
    private javax.swing.JComboBox<String> DatoA;
    private javax.swing.JComboBox<String> DenunciasC;
    private javax.swing.JTextField DniAC;
    private javax.swing.JTextField DniBC;
    private javax.swing.JTextField DniConductorA;
    private javax.swing.JTextField DniRB;
    private javax.swing.JTextField EmailAC;
    private javax.swing.JLabel EtiquetaApellidoAC;
    private javax.swing.JLabel EtiquetaBuscarRB;
    private javax.swing.JTextPane EtiquetaC;
    private javax.swing.JLabel EtiquetaCalleAC;
    private javax.swing.JLabel EtiquetaCausaA;
    private javax.swing.JLabel EtiquetaCodigoA;
    private javax.swing.JLabel EtiquetaConfirmaC;
    private javax.swing.JLabel EtiquetaContraseñaAC;
    private javax.swing.JLabel EtiquetaDatoA;
    private javax.swing.JLabel EtiquetaDenunciasC;
    private javax.swing.JLabel EtiquetaDniAC;
    private javax.swing.JLabel EtiquetaDniC;
    private javax.swing.JLabel EtiquetaDniConductorA;
    private javax.swing.JLabel EtiquetaEmailAC;
    private javax.swing.JLabel EtiquetaEscribirBC;
    private javax.swing.JLabel EtiquetaFechaC;
    private javax.swing.JLabel EtiquetaGafasLentillasAC;
    private javax.swing.JLabel EtiquetaImporteA;
    private javax.swing.JLabel EtiquetaMatriculaA;
    private javax.swing.JLabel EtiquetaMatriculasC;
    private javax.swing.JLabel EtiquetaNombreAC;
    private javax.swing.JLabel EtiquetaNombreC;
    private javax.swing.JLabel EtiquetaNombreL;
    private javax.swing.JLabel EtiquetaPasswordL;
    private javax.swing.JLabel EtiquetaTarjetaP;
    private javax.swing.JLabel EtiquetaTipoL;
    private javax.swing.JComboBox<String> GafasLentillasAC;
    private javax.swing.JTextField ImporteA;
    private javax.swing.JPanel Login;
    private javax.swing.JTextField MatriculaA;
    private javax.swing.JScrollPane MostrarDniC;
    private javax.swing.JScrollPane MostrarMatrículasC;
    private javax.swing.JScrollPane MostrarNombreC;
    private javax.swing.JTextField NombreAC;
    private javax.swing.JTextField NombreL;
    private javax.swing.JPasswordField PasswordAC;
    private javax.swing.JPasswordField PasswordL;
    private javax.swing.JDialog PopUpBajaConductor;
    private javax.swing.JDialog PopUpConfirma;
    private javax.swing.JDialog PopUpPagar;
    private javax.swing.JDialog PopUpRealizarBusqueda;
    private javax.swing.JTextField TarjetaP;
    private javax.swing.JComboBox<String> TipoL;
    private javax.swing.JPanel TrabajadorDGT;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JTextPane jTextPane2;
    private javax.swing.JTextPane jTextPane3;
    // End of variables declaration//GEN-END:variables
}
